### ISSUE TITLE
Styles are lost when building component

### ISSUE THREAD

**Issue by deRaaf** [EranGrin/vue-web-component-wrapper#15]
I created a web component from a wrapper component with several child components, when I import the component before building it has it's style complete:

![Scherm­afbeelding 2024-03-12 om 08 45 12](https://github.com/EranGrin/vue-web-component-wrapper/assets/16288270/e911936e-be65-4a50-8094-a8e6a5329e8e)

But after building the style block is empty:

![Scherm­afbeelding 2024-03-12 om 08 46 08](https://github.com/EranGrin/vue-web-component-wrapper/assets/16288270/63782b6d-24c0-442e-93a1-bc62c13bb330)

My setup is a s follows:

component.js
```
import {
  defineCustomElement as VueDefineCustomElement,
  h,
  createApp,
  getCurrentInstance
} from 'vue'
import { createWebComponent } from 'vue-web-component-wrapper'
import { createI18n } from 'vue-i18n'
import { config } from './helpers/i18n.helper'
import Component from './components/Component.vue'

const pluginsWrapper = {
  install(GivenVue) {
    const Vue = GivenVue
    const i18n = createI18n(config)
    Vue.use(i18n)
  }
}

createWebComponent({
  rootComponent: Component,
  elementName: 'custom-component'
  plugins: pluginsWrapper,
  VueDefineCustomElement,
  h,
  createApp,
  getCurrentInstance,
  disableStyleRemoval: true
})
```

App.vue
```
<script setup>
import './component';
</script>

<template>
    <custom-component></custom-component>
</template>
```

vite.config.js
```
export default defineConfig(() => {

  return {
  ...
    plugins: [
      vue({
        customElement: true
      }),
    ],
    build: {
      lib: {
        entry: './src/component.js',
        name: 'custom-component,
        fileName: 'custom-component'
      },
    },
  }
  ...
})
```

Let me know if you need additional info.

**Comment by EranGrin** [comment]
Hi There,
I would suggest to check the vite demo project [link](https://github.com/EranGrin/vue-web-component-wrapper/tree/main/demo-app-vite)

as I can see that you have a slightly different setup.
If you need further help it would be better if you could provide a stackblitz demo of the issue
Thanks

**Comment by deRaaf** [comment]
Hi,

I based my implementation on the demo, I only needed a different name for my output. Could the issue be that I use components from an extermal repository?

I could share a simplified setup but the external repo is private so I can't share my full implementation sadly.

**Comment by EranGrin** [comment]
> I based my implementation on the demo, I only needed a different name for my output. Could the issue be that I use components from an extermal repository?

This unlikely to happen.


If you could share a simplified version which reproduces the issue, I would be happy to assist

**Comment by WulfP** [comment]
@deRaaf  Just had a similar issue.
Checked the vite demo project and found that it is working perfectly.

Then compared my config to the demo and saw that dev-packages were missing.

After adding postcss with postcss.config.js (hat to rename it to .cjs) and autoprefixer all style-blocks were working again as expected.

Hope this helps!

**Comment by EranGrin** [comment]
@WulfP hmm... you claim that the plugin must have the postcss.config file ?
