### ISSUE TITLE
Styles in vue component are not applied

### ISSUE THREAD

**Issue by shwull** [EranGrin/vue-web-component-wrapper#16]
https://stackblitz.com/edit/vitejs-vite-exevhh?file=src%2Fmain.js,src%2FTest.vue,src%2FApp.vue&terminal=dev

![11111](https://github.com/EranGrin/vue-web-component-wrapper/assets/75296475/8bca9774-e3e3-425a-9031-1287cee60a77)

**Comment by EranGrin** [comment]
Hi There,
You only missing one configuration attribute

in the vite config you should add the custom element true 
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [vue({
    customElement: true,
  })],
})
```

**Comment by shwull** [comment]
oh, miss this. Thank you

**Comment by EranGrin** [comment]
Closing this Ticket

**Comment by EranGrin** [comment]
Missing one configuration attribute
