### ISSUE TITLE
how to deal a component of used webpack bulding by format umd

### ISSUE THREAD

**Issue by shwull** [EranGrin/vue-web-component-wrapper#17]
For example，a component named Test.vue，it exists in another gitClone, I can only see Test.js and Test.css。 These two files used build by webpack( target: 'umd')， how can I use this plugin by these two files?

![test](https://github.com/EranGrin/vue-web-component-wrapper/assets/75296475/9cf7e577-e768-4453-be3b-899497a6ccdf)

**Comment by EranGrin** [comment]
I'm not quite sure if I understand the issue, can you elaborate?

**Comment by EranGrin** [comment]
Hi  [shwull](https://github.com/shwull),
Please let me know if this issue is still relevant, or We can close this issue
