### ISSUE TITLE
No Vite hot reload when changing component

### ISSUE THREAD

**Issue by MichelJonkman** [EranGrin/vue-web-component-wrapper#21]
The component doesn't reload when I change it's code except for styling. If this isn't reproducible I can create a minimal project to reproduce it!

**Comment by EranGrin** [comment]
Please create a minimal project to reproduce the issue

**Comment by MichelJonkman** [comment]
I zipped the project as it was easier to share that way. If I run `pnpm dev`, open de url it gives and make changes to my component file, hot reload doesn't work.

[web-component.zip](https://github.com/user-attachments/files/15593113/web-component.zip)

**Comment by EranGrin** [comment]
@MichelJonkman great catch this bug seems to be related to the latest release and doesn't exist on v1.4.4.
I'll try to fix it in the coming days

**Comment by MichelJonkman** [comment]
@EranGrin Alright, thank you! Everything seems to be working fine otherwise

**Comment by EranGrin** [comment]
@MichelJonkman I added a bugfix, please let me know if all work as expected.

**Comment by MichelJonkman** [comment]
@EranGrin Seems to work correctly now!
