### ISSUE TITLE
How can I build this? 

### ISSUE THREAD

**Issue by kennyredstart** [EranGrin/vue-web-component-wrapper#23]
How can I build this so that I can import it as a module ? When using:
lib: {
            entry: './src/main.js',
            name: 'my-component'
            // the proper extensions will be added
            fileName: 'my-component'
        }

and importing externally as:
<script type="module" src="//localhost:4173/my-component.js"></script>

it doesn't work... 😞

**Comment by EranGrin** [comment]
Hi @kennyredstart,
I would be glad to help, but I am not quite sure what is the issue, did you try to use the demo project 
Demo files: https://github.com/EranGrin/vue-web-component-wrapper/tree/main/demo-app-vite
Live demo: https://stackblitz.com/edit/vue-web-component-wrapper?file=README.md&startScript=vite-demo

If this doesn't resolve your issue, please provide a more thorough explanation.

**Comment by EranGrin** [comment]
@kennyredstart please let me know if I can close this issue
