### ISSUE TITLE
shadowRoot prop casing mis-match in DefineCustomElementConfig type definition

### ISSUE THREAD

**Issue by OllyNicholass** [EranGrin/vue-web-component-wrapper#25]
https://github.com/EranGrin/vue-web-component-wrapper/blob/3063fa4ca8f36e3146b16fd5dcfcd4baf3ac9a7d/package/types.d.ts#L24

https://github.com/EranGrin/vue-web-component-wrapper/blob/3063fa4ca8f36e3146b16fd5dcfcd4baf3ac9a7d/package/src/api-custom-element.ts#L48

Causes errors on build using typescript:

```log
error TS2345: Argument of type '{ shadowRoot: boolean; }' is not assignable to parameter of type 'defineCustomElementSFCOptions'.
  Object literal may only specify known properties, but 'shadowRoot' does not exist in type 'defineCustomElementSFCOptions'. Did you mean to write 'ShadowRoot'?

10 export const NavBarLinkGroupCE = defineCustomElementSFC(NavBarLinkGroupVue as any, { shadowRoot: true });
```

**Comment by EranGrin** [comment]
Oh...wow, I'll push a bugfix version
Thank you

**Comment by EranGrin** [comment]
Closing the ticket as changes are part of the latest version
