### ISSUE TITLE
Warning about the __NO_SIDE_EFFECTS__ after building with vite

### ISSUE THREAD

**Issue by fabiiomiiguel** [EranGrin/vue-web-component-wrapper#41]
When I build my project with vite It throws this warning regarding the __NO_SIDE_EFFECTS_.
I found in a rollup issue the [solution](https://github.com/rollup/rollup/pull/5024#issuecomment-1580285756).

![Screenshot 2024-11-07 at 01 12 12](https://github.com/user-attachments/assets/d076097e-9722-4195-998e-0fa3429d7ffe)

Also when I build this project it also throws an warning related using named and default exports together. 
I also found in a rollup issue the [solution](https://github.com/rollup/rollup/issues/2106#issuecomment-482790635) to disable this warning.

![Screenshot 2024-11-07 at 01 58 17](https://github.com/user-attachments/assets/2c7e4e67-3009-4166-8eac-79a83b92bb50)

I did a pull request with a suggestion of a fix for both warnings.

- https://github.com/EranGrin/vue-web-component-wrapper/pull/40

**Comment by EranGrin** [comment]
Hi @fabiiomiiguel,
thank you for the Issue/PR, indeed I haven't tried to use rollup,
Would you mind sharing your working rollup setup vite config? I would be glad to add it to the docs.

**Comment by fabiiomiiguel** [comment]
Yes of course, this is the build configs that I use with vite.
```
...
    build: {
      emptyOutDir: true,
      target: 'ES2020',
      rollupOptions: {
        output: {
          entryFileNames: '[name].js',
        },
      },
      cssCodeSplit: false,
    },
...
```

EDIT: @EranGrin I create a simple project from the official Vue 3 template in StackBlitz, so you can see the error also

https://stackblitz.com/edit/vitejs-vite-16kd3r

**Comment by EranGrin** [comment]
The PR is Merged, and the docs are updated thanks, closing the issue now

**Comment by fabiiomiiguel** [comment]
@EranGrin sorry to bother you again.

I saw your new version and sadly the problem persists.
I think it's related with the first `/* #__NO_SIDE_EFFECTS__ */` manually added to the build.

I found out the solution in the [no-side-effects-notation-spec.md](https://github.com/javascript-compiler-hints/compiler-notations-spec/blob/main/no-side-effects-notation-spec.md), which is to remove the white spaces.

So if you don't mind could you please do the following steps so I don't need to do a new pull request.

1. Replace `/*! @__NO_SIDE_EFFECTS__ */` by `/*#__NO_SIDE_EFFECTS__*/` in the `package/src/api-custom-element.ts` file.

1.  Instead of adding `/* #__NO_SIDE_EFFECTS__ */` to the build add `/*#__NO_SIDE_EFFECTS__*/` in the file.

**Comment by EranGrin** [comment]
Second try 😄

**Comment by fabiiomiiguel** [comment]
@EranGrin when doing the build make sure we don't have spaces in `/*! #__NO_SIDE_EFFECTS__ */`.
Because your last commit as it in the [package/dist/vue-web-component-wrapper.es.js](https://github.com/EranGrin/vue-web-component-wrapper/commit/715e8088fecad5e03763be411e04864091ee10e9#diff-a4d331310c3c196c155f5b8f9328e1d670339e8ce0b380ee54381fb0dac895a5) and also [‎package/dist/vue-web-component-wrapper.umd.js](https://github.com/EranGrin/vue-web-component-wrapper/commit/715e8088fecad5e03763be411e04864091ee10e9#diff-5c8e27c2c339dbeb769517d78195785c77eedc28129a33cde4bbf019fdca538c).

**Comment by EranGrin** [comment]
I need to check why the build creates add this space, I am quite busy this week so it will take a few days, thanks

**Comment by EranGrin** [comment]
Hi @fabiiomiiguel, I updated all packages.
If you have a moment, please check this branch https://github.com/EranGrin/vue-web-component-wrapper/tree/bugfix/rollup-no-side-effect

**Comment by fabiiomiiguel** [comment]
Hello I did test and it works now 🥳

I also did a pull request https://github.com/EranGrin/vue-web-component-wrapper/pull/45 based on that branch.
I tested with your original `/*! #__NO_SIDE_EFFECTS__ */` comment and with this branch the build also works, so I think it's better to keep it as you had before!

Thanks!

**Comment by EranGrin** [comment]
@fabiiomiiguel  I closed your PR as based on my checks and reading the issue was related to ESLint version, instead I merged another PR based on the branch I shared earlier https://github.com/EranGrin/vue-web-component-wrapper/pull/48

please let me know if I can close the issue as well.

**Comment by fabiiomiiguel** [comment]
Sure, sorry about that. It works in this new version. No more warnings 😁
