### ISSUE TITLE
Slot processing with nested elements when disableShadowDOM: true

### ISSUE THREAD

**Issue by thanhbican** [EranGrin/vue-web-component-wrapper#44]
When `disableShadowDOM: true` is set, there are significant issues with slot handling in nested components

_this is source code of vue-web-component-wrapper_

```javascript
// Replace slot
if (!this._config.shadowRoot) {
  this._slots = {};
  for (const child of Array.from(this.children)) {
    const slotName = child.getAttribute('slot') || 'default';
    if (!this._slots[slotName]) {
      this._slots[slotName] = [];
    }
    this._slots[slotName].push(
      h(child.tagName.toLowerCase(), {}, child.innerHTML)
    );
  }
  this.replaceChildren();
}
```
On the line `h(child.tagName.toLowerCase(), {}, child.innerHTML),` the function handling slots processes only basic HTML tags. This results in the following limitations:

## 1. Basic Text Not Rendered
The text `abc` does not render.

```html
<xx-component name="core-btn">abc</xx-component>
```

## 2. Inner HTML as Text Output Only
`<h1>abc</h1>` only outputs the text as-is

```html
<div slot="prev">
  <h1>abc</h1>
</div>
```

## 3. Attributes Are Lost
In this case, attributes such as `class="text-red"`  and `id="test"` are stripped because the h function returns an empty object {} for attributes.

```html
<xx-component name="core-btn">
  <div class="text-red" id="test">abc</div>
</xx-component>
```

## 4.Not support nested component like `<xx-component>` in side `<xx-component>`

**Comment by thanhbican** [comment]
I have created a PR to address this issue: https://github.com/EranGrin/vue-web-component-wrapper/pull/43.
Kindly take a look.

**Comment by EranGrin** [comment]
Hi @thanhbican, thank you for the issue & PR, but, would you mind creating a stackblitz example that demonstrates the issue?

**Comment by thanhbican** [comment]
Hi @EranGrin, thanks for your reply.

I've created a demonstration here: [https://stackblitz.com/~/github.com/thanhbican/web-component-no-shadow-dom-demo?file=index.html](https://stackblitz.com/~/github.com/thanhbican/web-component-no-shadow-dom-demo?file=index.html)

You can check the index.html file, I've added comments in it.

**Comment by EranGrin** [comment]
Hi @thanhbican, your PR is merged, and I would like to close the issue
Thank you 👍

**Comment by thanhbican** [comment]
@EranGrin Sorry, but can you run `npm run build` in the package?

The `/package/dist` directory is not up to date.
