### ISSUE TITLE
Error when running vite demo on current github version. Stackblitz version works fine

### ISSUE THREAD

**Issue by mophima** [EranGrin/vue-web-component-wrapper#5]
Hey, 

I have tried your project and I encountered an error when running the vite demo from the downloaded source files:
![grafik](https://github.com/EranGrin/vue-web-component-wrapper/assets/12238758/ff6a280f-810b-4b09-83a1-e40bb13afb74)

I do get a similar error when I try to use your wrapper in my own project (via npm install). 
I also tried to download the source code of yout Stackblitz example, which works fine:
![grafik](https://github.com/EranGrin/vue-web-component-wrapper/assets/12238758/a9e53945-7aa7-4844-a9fe-b2210633b88a)

Maybe you can take a look?

**Comment by EranGrin** [comment]
I'll check it this evening, thanks

**Comment by EranGrin** [comment]
Hello Moritz, I would suggest you check the project first in stackblitz [project link](https://stackblitz.com/edit/vue-web-
component-wrapper?file=README.md&startScript=vite-demo)
if you still didn't mange to make it working, ping me again and we will debug it

**Comment by mophima** [comment]
> Hello Moritz, I would suggest you check the project first in stackblitz [project link](https://stackblitz.com/edit/vue-web- component-wrapper?file=README.md&startScript=vite-demo) if you still didn't mange to make it working, ping me again and we will debug it

Hey Eran, 
as I wrote in my first post I did try the code from Stackblitz, which I downloaded directly from there and it does work fine. My Issues however persists with the newest version of the main branch here on github

**Comment by mophima** [comment]
To add to that: I also tried to construct a minimal example, basically just installing the vue-web-component-wrapper and changing the main.js file: https://stackblitz.com/edit/vitejs-vite-cssrks?file=package.json

**Comment by mophima** [comment]
With some further Testing I can confirm that the Issue lies with the newest version 1.1.0
With my Stackblitz Example above, I got it working with version 1.0.5

**Comment by kcleong** [comment]
I also have the same problem, `1.0.5` works (see https://gist.github.com/kcleong/7dc901b660eaf2fc90cc227cc5d968de) but `1.1.0` does not (see https://gist.github.com/kcleong/722d8008858a4514424438a7074a5430)

**Comment by EranGrin** [comment]
Alrighty, this narrows down the issue, I'll push a bugfix later on today.
Thanks for the issue finding

**Comment by EranGrin** [comment]
Hi There, 
I released a new version with fixes,
hopefully, this will resolve this silly issue.

**Comment by mophima** [comment]
works for me now, thank you!
